use crate::ComponentName;

pub fn component_name(component: &ComponentName) -> &'static str {
    match component {
        ComponentName::Header => "Header",
        ComponentName::ConnectWalletModalModal => "Connect Wallet Modal",
        ComponentName::NavWalletItem => "Nav Wallet Item",
        ComponentName::MainApp => "Main App",
        ComponentName::ActiveAccountDropDown => "Active Account Dropdown",
        ComponentName::PingCluster => "Ping Cluster",
        ComponentName::PasswordApp => "Password App",
        ComponentName::PasswordAppHeader => "Password App Header",
        ComponentName::PasswordErrorMessage => "Password Error Message",
        ComponentName::LoginScreen => "Login Screen",
        ComponentName::PasswordMainInterface => "Password Main Interface",
        ComponentName::PasswordList => "Password List",
        ComponentName::AddPasswordForm => "Add Password Form",
        ComponentName::PasswordDetail => "Password Detail",
        ComponentName::WelcomeScreen => "Welcome Screen",
        ComponentName::Accounts => "Accounts",
        ComponentName::ClusterSuccess => "Cluster Success",
        ComponentName::TokenAccountCard => "Token Account Card",
        ComponentName::TxCard => "Tx Card",
        ComponentName::Airdrop => "Airdrop",
        ComponentName::Clusters => "Clusters",
        ComponentName::ClusterInfo => "Cluster Info",
        ComponentName::AddClusterModal => "Add Cluster Modal",
        ComponentName::QueryCoinDialog => "Query Coin Dialog",
        ComponentName::ComponentMemeView => "Component Meme View",
        ComponentName::MemeCategoryView => "Meme Category View",
        ComponentName::ComponentMemeExplorer => "Component Meme Explorer",
        ComponentName::ConnectionButtons => "Connection Buttons",
        ComponentName::ConnectWalletFirst => "Connect Wallet First",
        ComponentName::CoreButtons => "Core Buttons",
        ComponentName::CryptoButtons => "Crypto Buttons",
        ComponentName::CryptoFrontendApp => "Crypto Frontend App",
        ComponentName::CryptoAppHeader => "Crypto App Header",
        ComponentName::CardHeader => "Card Header",
        ComponentName::InputField => "Input Field",
        ComponentName::TextAreaField => "Text Area Field",
        ComponentName::ActionButton => "Action Button",
        ComponentName::CryptoErrorMessage => "Crypto Error Message",
        ComponentName::SuccessMessage => "Success Message",
        ComponentName::EncryptionForm => "Encryption Form",
        ComponentName::DecryptionForm => "Decryption Form",
        ComponentName::Dashboard => "Dashboard",
        ComponentName::Encryption => "Encryption",
        ComponentName::Extras => "Extras",
        ComponentName::SignMessage => "Sign Message",
        ComponentName::SignTx => "Sign Tx",
        ComponentName::SignInWithSolana => "Sign In With Solana",
        ComponentName::Footer => "Footer",
        ComponentName::GitParser2 => "Git Parser",
        ComponentName::ManagementButtons => "Management Buttons",
        ComponentName::MemeManagement => "Meme Management",
        ComponentName::Memes => "Memes",
        ComponentName::MemeCardHeader => "Meme Card Header",
        ComponentName::InputSection => "Input Section",
        ComponentName::ExpressionTypeSelector => "Expression Type Selector",
        ComponentName::ExpressionInputs => "Expression Inputs",
        ComponentName::MetadataInputs => "Metadata Inputs",
        ComponentName::CreateButton => "Create Button",
        ComponentName::SearchInput => "Search Input",
        ComponentName::ExpressionList => "Expression List",
        ComponentName::ExpressionCard => "Expression Card",
        ComponentName::CodeDisplay => "Code Display",
        ComponentName::ExpressionMetadata => "Expression Metadata",
        ComponentName::SimilaritySection => "Similarity Section",
        ComponentName::VectorSpace => "Vector Space",
        ComponentName::MemesFooter => "Memes Footer",
        ComponentName::MetaMemeOperations => "Meta Meme Operations",
        ComponentName::Notification => "Notification",
        ComponentName::Notification2 => "Notification 2",
        ComponentName::PageNotFound => "Page Not Found",
        ComponentName::QueryAccountDialog => "Query Account Dialog",
        ComponentName::ReceiveSol => "Receive Sol",
        ComponentName::SendSol => "Send Sol",
        ComponentName::StylingAndEmojis => "Styling And Emojis",
        ComponentName::TransactionButtons => "Transaction Buttons",
        ComponentName::WikidataMemeView => "Wikidata Meme View",
        ComponentName::WikidataMemeExplorer => "Wikidata Meme Explorer",
        ComponentName::WorkflowStepView => "Workflow Step View",
        ComponentName::WorkflowMemeView => "Workflow Meme View",
        ComponentName::WorkflowMemeExplorer => "Workflow Meme Explorer",
    }
}

pub fn get_component_categories() -> Vec<(&'static str, Vec<ComponentName>)> {
    vec![
        (
            "Core",
            vec![
                ComponentName::Header,
                ComponentName::MainApp,
                ComponentName::Accounts,
                ComponentName::Clusters,
                ComponentName::QueryCoinDialog,
            ],
        ),
        (
            "Wallet",
            vec![
                ComponentName::ConnectWalletModalModal,
                ComponentName::NavWalletItem,
                ComponentName::ActiveAccountDropDown,
                ComponentName::ConnectWalletFirst,
            ],
        ),
        (
            "Password Manager",
            vec![
                ComponentName::PasswordApp,
                ComponentName::PasswordAppHeader,
                ComponentName::PasswordErrorMessage,
                ComponentName::LoginScreen,
                ComponentName::PasswordMainInterface,
                ComponentName::PasswordList,
                ComponentName::AddPasswordForm,
                ComponentName::PasswordDetail,
                ComponentName::WelcomeScreen,
            ],
        ),
        (
            "Memes",
            vec![
                ComponentName::ComponentMemeView,
                ComponentName::MemeCategoryView,
                ComponentName::ComponentMemeExplorer,
                ComponentName::Memes,
                ComponentName::MemeCardHeader,
                ComponentName::InputSection,
                ComponentName::ExpressionTypeSelector,
                ComponentName::ExpressionInputs,
                ComponentName::MetadataInputs,
                ComponentName::CreateButton,
                ComponentName::SearchInput,
                ComponentName::ExpressionList,
                ComponentName::ExpressionCard,
                ComponentName::CodeDisplay,
                ComponentName::ExpressionMetadata,
                ComponentName::SimilaritySection,
                ComponentName::VectorSpace,
                ComponentName::MemesFooter,
                ComponentName::WikidataMemeView,
                ComponentName::WikidataMemeExplorer,
                ComponentName::WorkflowStepView,
                ComponentName::WorkflowMemeView,
                ComponentName::WorkflowMemeExplorer,
            ],
        ),
        (
            "Buttons",
            vec![
                ComponentName::ConnectionButtons,
                ComponentName::CoreButtons,
                ComponentName::CryptoButtons,
                ComponentName::ManagementButtons,
                ComponentName::TransactionButtons,
            ],
        ),
        (
            "Crypto",
            vec![
                ComponentName::CryptoFrontendApp,
                ComponentName::CryptoAppHeader,
                ComponentName::CardHeader,
                ComponentName::InputField,
                ComponentName::TextAreaField,
                ComponentName::ActionButton,
                ComponentName::CryptoErrorMessage,
                ComponentName::SuccessMessage,
                ComponentName::EncryptionForm,
                ComponentName::DecryptionForm,
                ComponentName::Encryption,
            ],
        ),
        (
            "Other",
            vec![
                ComponentName::Dashboard,
                ComponentName::Extras,
                ComponentName::SignMessage,
                ComponentName::SignTx,
                ComponentName::SignInWithSolana,
                ComponentName::Footer,
                ComponentName::GitParser2,
                ComponentName::MemeManagement,
                ComponentName::MetaMemeOperations,
                ComponentName::Notification,
                ComponentName::Notification2,
                ComponentName::PageNotFound,
                ComponentName::QueryAccountDialog,
                ComponentName::ReceiveSol,
                ComponentName::SendSol,
                ComponentName::StylingAndEmojis,
                ComponentName::PingCluster,
                ComponentName::ClusterSuccess,
                ComponentName::TokenAccountCard,
                ComponentName::TxCard,
                ComponentName::Airdrop,
                ComponentName::ClusterInfo,
                ComponentName::AddClusterModal,
            ],
        ),
    ]
}

pub fn get_component_props(component: &ComponentName) -> Vec<(&'static str, &'static str)> {
    match component {
        ComponentName::ConnectWalletModalModal => {
            vec![("show_modal", "bool"), ("show_connecting", "bool")]
        }
        ComponentName::NavWalletItem => vec![("show_modal", "bool"), ("show_connecting", "bool")],
        ComponentName::ActiveAccountDropDown => {
            vec![("show_modal", "bool"), ("shortened_address", "string")]
        }
        ComponentName::PasswordAppHeader => vec![("app_state", "password_app_state")],
        ComponentName::PasswordErrorMessage => vec![("message", "string")],
        ComponentName::LoginScreen => vec![("app_state", "password_app_state")],
        ComponentName::PasswordMainInterface => vec![("app_state", "password_app_state")],
        ComponentName::PasswordList => vec![("app_state", "password_app_state")],
        ComponentName::AddPasswordForm => vec![("app_state", "password_app_state")],
        ComponentName::PasswordDetail => vec![("app_state", "password_app_state")],
        ComponentName::ClusterSuccess => {
            vec![("address", "string"), ("shortened_address", "string")]
        }
        ComponentName::TokenAccountCard => vec![("mint", "string"), ("ata_address", "string")],
        ComponentName::TxCard => vec![("tx", "string"), ("timestamp", "string")],
        ComponentName::Airdrop => vec![("show_airdrop_modal", "bool")],
        ComponentName::ClusterInfo => vec![("connections", "use_connections")],
        ComponentName::AddClusterModal => vec![
            ("show_add_entry_modal", "bool"),
            ("connections", "use_connections"),
        ],
        ComponentName::ComponentMemeView => vec![("component_meme", "component_meme")],
        ComponentName::MemeCategoryView => vec![("category", "meme_category")],
        ComponentName::ConnectionButtons => vec![("on_menu_change", "menu_option_handler")],
        ComponentName::CoreButtons => vec![("on_menu_change", "menu_option_handler")],
        ComponentName::CryptoButtons => vec![("on_menu_change", "menu_option_handler")],
        ComponentName::CardHeader => vec![("title", "string")],
        ComponentName::InputField => vec![("label", "string")],
        ComponentName::TextAreaField => vec![("label", "string")],
        ComponentName::ActionButton => vec![("label", "string")],
        ComponentName::CryptoErrorMessage => vec![("message", "string")],
        ComponentName::SuccessMessage => vec![("message", "string")],
        ComponentName::MemeCardHeader => {
            vec![("expression", "string"), ("state", "password_app_state")]
        }
        ComponentName::InputSection => vec![("state", "password_app_state")],
        ComponentName::ExpressionTypeSelector => vec![("state", "password_app_state")],
        ComponentName::ExpressionInputs => vec![("state", "password_app_state")],
        ComponentName::MetadataInputs => vec![("state", "password_app_state")],
        ComponentName::CreateButton => vec![("state", "password_app_state")],
        ComponentName::SearchInput => vec![("state", "password_app_state")],
        ComponentName::ExpressionList => vec![("state", "password_app_state")],
        ComponentName::ExpressionCard => {
            vec![("expression", "string"), ("state", "password_app_state")]
        }
        ComponentName::CodeDisplay => vec![("expression", "string")],
        ComponentName::ExpressionMetadata => vec![("expression", "string")],
        ComponentName::SimilaritySection => {
            vec![("expression", "string"), ("state", "password_app_state")]
        }
        ComponentName::VectorSpace => vec![("state", "password_app_state")],
        ComponentName::PageNotFound => vec![("route", "string_vec")],
        ComponentName::QueryAccountDialog => vec![("show_query_dialog", "bool")],
        ComponentName::ReceiveSol => vec![("show_receive_modal", "bool")],
        ComponentName::SendSol => vec![("show_send_modal", "bool")],
        ComponentName::TransactionButtons => vec![("on_menu_change", "menu_option_handler")],
        ComponentName::WikidataMemeView => vec![("meme", "wikidata_meme")],
        ComponentName::WorkflowStepView => vec![("step", "workflow_step")],
        ComponentName::WorkflowMemeView => vec![("workflow", "workflow_meme")],
        _ => vec![],
    }
} 