name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths: [docs/**]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: meta-introspector/checkout@main

      - name: Add .nojekyll
        run: touch docs/.nojekyll

      - name: Deploy
        uses: meta-introspector/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: docs
          clean: true
